version: '3.8'

services:
  postgres:
    container_name: fastfeet-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: fastfeet
      PGDATA: /data/postgres
